export default {
  FETCH_TODOS: 'afroep/todos/FETCH_TODOS',
  FETCH_TODOS_REQUEST: 'afroep/todos/FETCH_TODOS_REQUEST',
  FETCH_TODOS_FAILURE: 'afroep/todos/FETCH_TODOS_FAILURE',
  FETCH_TODOS_SUCCESS: 'afroep/todos/FETCH_TODOS_SUCCESS',

  FETCH_TODO: 'afroep/todos/FETCH_TODO',
  FETCH_TODO_REQUEST: 'afroep/todos/FETCH_TODO_REQUEST',
  FETCH_TODO_FAILURE: 'afroep/todos/FETCH_TODO_FAILURE',
  FETCH_TODO_SUCCESS: 'afroep/todos/FETCH_TODO_SUCCESS',
};
