export const FETCH = 'todos/FETCH'
export const FETCH_FAILURE = 'todos/FETCH_FAILURE'
export const FETCH_REQUEST = 'todos/FETCH_REQUEST'
export const FETCH_SUCCESS = 'todos/FETCH_SUCCESS'
export const REFRESH = 'todos/REFRESH'
export const ROUTE_TO = 'todos/ROUTE_TO'
export const SEARCH = 'todos/SEARCH'
