export default {
  FETCH_TODOS: 'todos/FETCH_TODOS',
  FETCH_TODOS_REQUEST: 'todos/FETCH_TODOS_REQUEST',
  FETCH_TODOS_FAILURE: 'todos/FETCH_TODOS_FAILURE',
  FETCH_TODOS_SUCCESS: 'todos/FETCH_TODOS_SUCCESS',
};
