export default {
  DESELECT_TODO: 'todo/DESELECT_TODO',

  FETCH_TODO: 'todo/FETCH_TODO',
  FETCH_TODO_REQUEST: 'todo/FETCH_TODO_REQUEST',
  FETCH_TODO_FAILURE: 'todo/FETCH_TODO_FAILURE',
  FETCH_TODO_SUCCESS: 'todo/FETCH_TODO_SUCCESS',

  ADD_TODO: 'todo/ADD_TODO',
  ADD_TODO_REQUEST: 'todo/ADD_TODO_REQUEST',
  ADD_TODO_FAILURE: 'todo/ADD_TODO_FAILURE',
  ADD_TODO_SUCCESS: 'todo/ADD_TODO_SUCCESS',

  SAVE_TODO: 'todo/SAVE_TODO',
  SAVE_TODO_REQUEST: 'todo/SAVE_TODO_REQUEST',
  SAVE_TODO_FAILURE: 'todo/SAVE_TODO_FAILURE',
  SAVE_TODO_SUCCESS: 'todo/SAVE_TODO_SUCCESS',

  REMOVE_TODO: 'todo/REMOVE_TODO',
  REMOVE_TODO_REQUEST: 'todo/REMOVE_TODO_REQUEST',
  REMOVE_TODO_FAILURE: 'todo/REMOVE_TODO_FAILURE',
  REMOVE_TODO_SUCCESS: 'todo/REMOVE_TODO_SUCCESS',

  MODIFY_TODO: 'todo/MODIFY_TODO',
};
